#!/usr/bin/env -S uv run python
"""Drift-prevention script to generate the environment variables table and .env.example."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
README = REPO_ROOT / "README.md"
ENV_EXAMPLE = REPO_ROOT / ".env.example"


def format_default(val: Any) -> str:
    if val == "":
        return "empty"
    if val == []:
        return "`[]`"
    if isinstance(val, bool):
        return f"`{'true' if val else 'false'}`"
    return f"`{val}`"


def format_env_example_val(val: Any) -> str:
    if val == "":
        return ""
    if isinstance(val, bool):
        return "true" if val else "false"
    if isinstance(val, list):
        return json.dumps(val)
    return str(val)


def main() -> int:
    from h4ckath0n.config import Settings

    # Build Markdown Table and Env Example
    table_lines = ["| Variable | Default | Description |", "|---|---|---|"]

    env_example_lines = ["# Generated by scripts/check_doc_env.py", ""]

    # Extra alias not defined via settings directly
    extra_aliases = {
        "openai_api_key": (
            "OPENAI_API_KEY",
            "empty",
            "OpenAI API key for the LLM wrapper",
        )
    }

    for field_name, field_info in Settings.model_fields.items():
        env_var = f"H4CKATH0N_{field_name.upper()}"
        default_val = format_default(field_info.default)
        env_default_val = format_env_example_val(field_info.default)
        desc = field_info.description or ""

        # Special case additions to match prior handwritten table
        if field_name == "rp_id":
            default_val = "`localhost` in development"
        elif field_name == "origin":
            default_val = "`http://localhost:8000` in development"
        elif field_name == "openai_api_key":
            # Alias var documented above h4ckath0n var
            alias_var, alias_default, alias_desc = extra_aliases[field_name]
            table_lines.append(f"| `{alias_var}` | {alias_default} | {alias_desc} |")

        table_lines.append(f"| `{env_var}` | {default_val} | {desc} |")
        env_example_lines.append(f"# {desc}")
        env_example_lines.append(f"{env_var}={env_default_val}")
        env_example_lines.append("")

    table_content = "\n".join(table_lines)

    # Update README in place
    readme_text = README.read_text()

    start_marker = "<!-- START_ENV_DOCS -->"
    end_marker = "<!-- END_ENV_DOCS -->"

    pattern = re.compile(
        rf"{re.escape(start_marker)}.*?{re.escape(end_marker)}", re.DOTALL
    )

    if not pattern.search(readme_text):
        print("❌ Markers not found in README.md")
        return 1

    new_text = pattern.sub(
        f"{start_marker}\n{table_content}\n{end_marker}", readme_text
    )

    changed = False
    if new_text != readme_text:
        README.write_text(new_text)
        changed = True

    if not ENV_EXAMPLE.exists() or ENV_EXAMPLE.read_text() != "\n".join(
        env_example_lines
    ):
        ENV_EXAMPLE.write_text("\n".join(env_example_lines))
        changed = True

    if changed:
        print(
            "✍️ Updated README.md and .env.example with configuration values.\n"
            "Please commit the changes."
        )
        if "--check" in sys.argv:
            return 1
    else:
        print("✅ Documentation is up to date.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
